### ISSUE TITLE
Cant add new Patient

### ISSUE THREAD

**Issue by brandxp1** [CodeColors/EMSHub#2]
Halo, I can't add a new Patient..

You have fixed the first error now i got the next.

https://youtu.be/nTdaJSOqpvE

**Comment by CodeColors** [comment]
Okay, sorry for this problem,
You only need to enter a number in the price entry. It automatically formats in dollar format.

I will update this so that you can set the currency.

**Comment by CodeColors** [comment]
Keep me informed. Thank's for using this website !
